# -*- coding: utf-8 -*-
"""AMDS_Dictionary_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSeeaW76Q87eTjRD58aQZmoVAk9LktbO
"""

# Problem 1: Number, Square and Cube Table

print("Number, Square and Cube Table")
print("Enter a positive integer.")

n = int(input("Enter n: "))

print("\nNumber\tSquare\tCube")

for number in range(1, n + 1):
    square = number ** 2
    cube = number ** 3
    print(f"{number}\t{square}\t{cube}")

# Problem 2: Sum and Average of Even Numbers

print("Sum and Average of Even Numbers")
print("Enter a positive integer.")

n = int(input("Enter n: "))

total = 0
count = 0

print("\nEven numbers:", end=" ")

for number in range(1, n + 1):
    if number % 2 == 0:
        print(number, end=" ")
        total += number
        count += 1

print()

if count > 0:
    average = total / count
else:
    average = 0

print("Sum:", total)
print("Average:", average)

# Problem 3: Multiplication Table

print("Multiplication Table")
print("Enter an integer.")

number = int(input("Enter a number: "))

print()

for multiplier in range(1, 13):
    product = number * multiplier
    print(f"{number} * {multiplier} = {product}")

# Problem 4: Factorial Calculation

print("Factorial Calculation")
print("Enter a nonnegative integer.")

n = int(input("Enter n: "))

factorial = 1

if n == 0:
    print("0! = 1")
else:
    for number in range(1, n + 1):
        factorial *= number

    for number in range(1, n + 1):
        if number < n:
            print(number, end=" * ")
        else:
            print(number, end="")

    print(" =", factorial)

# Problem 5: Prime Number Checker

print("Prime Number Checker")

number = int(input("Enter an integer greater than 1: "))

is_prime = True
first_divisor = None

for divisor in range(2, number):
    if number % divisor == 0:
        is_prime = False
        first_divisor = divisor
        break

if is_prime:
    print(f"{number} is a prime number.")
else:
    print(f"{number} is not prime. Its first divisor is {first_divisor}.")

# Problem 6: Right Angled Number Pattern

print("Right Angled Number Pattern")
print("Enter the number of rows.")

rows = int(input("Enter the number of rows: "))

total_values = 0

for row in range(1, rows + 1):
    for number in range(1, row + 1):
        print(number, end=" ")
        total_values += 1
    print()

print("Total values printed:", total_values)

# Problem 7: Student Profile Manager

student = {
    "name": "Sara",
    "id": "CSE2026",
    "program": "Computer Science",
    "year": 2
}

print("Student Profile Manager")

# (a) Display original dictionary
print("\nOriginal Dictionary:")
print(student)

# (b) Update year of study
new_year = int(input("\nEnter the new year of study: "))
student["year"] = new_year

# (c) Add email
email = input("Enter the student's email: ")
student["email"] = email

# (d) Display each key and value
print("\nUpdated Student Profile:")
for key, value in student.items():
    print(key, ":", value)

# (e) Check for phone key
if "phone" in student:
    print("\nPhone number exists.")
else:
    print("\nPhone number does not exist.")

# Problem 8: Student Marks and Class Summary

marks = {
    "Alice": 82,
    "Bob": 58,
    "Charlie": 91,
    "David": 91,
    "Eva": 67
}

print("Student Marks and Class Summary\n")

# (a) Display names and marks
total_marks = 0
student_count = 0

highest_mark = None
top_students = []

for name, mark in marks.items():
    print(name, ":", mark)

    total_marks += mark
    student_count += 1

    if highest_mark is None or mark > highest_mark:
        highest_mark = mark
        top_students = [name]
    elif mark == highest_mark:
        top_students.append(name)

# (b) Calculate class average
average = total_marks / student_count

print("\nClass Average:", average)

# (c) Highest mark
print("Highest Mark:", highest_mark)
print("Top Student(s):", ", ".join(top_students))

# (d) Students scoring at least 60
print("\nStudents scoring at least 60:")
for name, mark in marks.items():
    if mark >= 60:
        print(name)

# Problem 9: Word-Frequency Counter

print("Word-Frequency Counter")

sentence = input("Enter a sentence: ").lower()

words = sentence.split()

frequency = {}

for word in words:
    if word in frequency:
        frequency[word] += 1
    else:
        frequency[word] = 1

print("\nWord Frequencies:")

for word, count in frequency.items():
    print(word + ":", count)

# Problem 10: Store Inventory Value

prices = {
    "rice": 75.0,
    "oil": 185.0,
    "milk": 95.0,
    "eggs": 12.0
}

quantities = {
    "rice": 20,
    "oil": 10,
    "milk": 15,
    "eggs": 60
}

print("Store Inventory Value\n")

total_inventory_value = 0

highest_product = None
highest_stock_value = None

for product in prices:
    stock_value = prices[product] * quantities[product]
    print(product, ":", stock_value)

    total_inventory_value += stock_value

    if highest_stock_value is None or stock_value > highest_stock_value:
        highest_stock_value = stock_value
        highest_product = product

print("\nTotal Inventory Value:", total_inventory_value)
print("Product with Highest Stock Value:", highest_product)
print("Highest Stock Value:", highest_stock_value)

# Problem 11: Character Frequency Analysis

print("Character Frequency Analysis")
print("Enter a line of text.")

text = input("Enter text: ").lower()

frequency = {}

for character in text:
    if character.isalpha():
        if character in frequency:
            frequency[character] += 1
        else:
            frequency[character] = 1

print("\nCharacter Frequencies:")

for character in sorted(frequency):
    print(character + ":", frequency[character])

# Problem 12: Updating Stock from a Delivery

stock = {
    "pen": 25,
    "notebook": 12,
    "marker": 8
}

delivery = {
    "notebook": 10,
    "marker": 5,
    "eraser": 20
}

print("Updating Stock from Delivery\n")

for product, quantity in delivery.items():
    if product in stock:
        stock[product] += quantity
    else:
        stock[product] = quantity

print("Updated Stock:")

total_items = 0

for product in sorted(stock):
    print(product + ":", stock[product])
    total_items += stock[product]

print("\nTotal Items in Stock:", total_items)

# Problem 13: Countdown with Input Validation

print("Countdown with Input Validation")

number = int(input("Enter a positive integer: "))

while number <= 0:
    print("Invalid input. Try again.")
    number = int(input("Enter a positive integer: "))

print()

while number > 0:
    print(number, end=" ")
    number -= 1

print("\nLaunch!")

# Problem 14: Digit Sum, Count and Reverse

print("Digit Sum, Count and Reverse")
print("Enter a positive integer.")

number = int(input("Enter a positive integer: "))

original_number = number
digit_count = 0
digit_sum = 0
reversed_number = 0

while number > 0:
    digit = number % 10
    digit_sum += digit
    digit_count += 1
    reversed_number = reversed_number * 10 + digit
    number //= 10

print("\nNumber of digits:", digit_count)
print("Sum of digits:", digit_sum)
print("Reversed number:", reversed_number)

# Problem 15: Three Attempt PIN Verification

correct_pin = "2468"

print("Three Attempt PIN Verification")

attempts = 0

while attempts < 3:
    pin = input("Enter your PIN: ")

    if pin == correct_pin:
        print("Access granted")
        break
    else:
        attempts += 1

        if attempts < 3:
            remaining = 3 - attempts
            print("Incorrect PIN.")
            print("Attempts remaining:", remaining)
        else:
            print("Account locked")

# Problem 16: Number-Guessing Game

import random

print("Number Guessing Game")
print("Guess the secret number between 1 and 100.")

secret_number = random.randint(1, 100)
attempts = 0

while True:
    guess = int(input("Enter your guess (1-100): "))

    if guess < 1 or guess > 100:
        print("Invalid guess. Enter a number between 1 and 100.")
        continue

    attempts += 1

    if guess < secret_number:
        print("Too low")
    elif guess > secret_number:
        print("Too high")
    else:
        print("Correct!")
        print("Total valid attempts:", attempts)
        break

# Problem 17: Contact Book

contacts = {}

while True:
    print("\nContact Book")
    print("1. Add or update a contact")
    print("2. Search for a contact")
    print("3. Delete a contact")
    print("4. Display all contacts")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        name = input("Enter name: ")
        phone = input("Enter phone number: ")
        contacts[name] = phone
        print("Contact saved.")

    elif choice == "2":
        name = input("Enter name to search: ")
        if name in contacts:
            print(name, ":", contacts[name])
        else:
            print("Contact not found.")

    elif choice == "3":
        name = input("Enter name to delete: ")
        if name in contacts:
            del contacts[name]
            print("Contact deleted.")
        else:
            print("Contact not found.")

    elif choice == "4":
        if len(contacts) == 0:
            print("No contacts available.")
        else:
            print("\nContacts:")
            for name in sorted(contacts):
                print(name, ":", contacts[name])

    elif choice == "5":
        print("Exiting Contact Book.")
        break

    else:
        print("Invalid choice.")

# Problem 18: Grocery Inventory System

inventory = {
    "rice": {"price": 75.0, "quantity": 20},
    "milk": {"price": 95.0, "quantity": 15}
}

while True:
    print("\nGrocery Inventory System")
    print("1. Add a new product")
    print("2. Restock a product")
    print("3. Sell a product")
    print("4. Display all products")
    print("5. Display total inventory value")
    print("6. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        product = input("Product name: ")
        price = float(input("Price: "))
        quantity = int(input("Quantity: "))

        if price < 0 or quantity < 0:
            print("Price and quantity cannot be negative.")
        else:
            inventory[product] = {"price": price, "quantity": quantity}
            print("Product added.")

    elif choice == "2":
        product = input("Product name: ")
        if product in inventory:
            quantity = int(input("Quantity to add: "))
            if quantity < 0:
                print("Quantity cannot be negative.")
            else:
                inventory[product]["quantity"] += quantity
                print("Stock updated.")
        else:
            print("Product not found.")

    elif choice == "3":
        product = input("Product name: ")
        if product in inventory:
            quantity = int(input("Quantity to sell: "))
            if quantity < 0:
                print("Quantity cannot be negative.")
            elif quantity > inventory[product]["quantity"]:
                print("Insufficient stock.")
            else:
                inventory[product]["quantity"] -= quantity
                print("Sale completed.")
        else:
            print("Product not found.")

    elif choice == "4":
        print("\nProducts:")
        for product in sorted(inventory):
            price = inventory[product]["price"]
            quantity = inventory[product]["quantity"]
            value = price * quantity
            print(f"{product}: Price={price}, Quantity={quantity}, Stock Value={value}")

    elif choice == "5":
        total_value = 0
        for product in inventory:
            total_value += (
                inventory[product]["price"] *
                inventory[product]["quantity"]
            )
        print("Total Inventory Value:", total_value)

    elif choice == "6":
        print("Exiting Inventory System.")
        break

    else:
        print("Invalid choice.")

# Problem 19: Student Record and Grade Manager

students = {}

while True:
    print("\nStudent Record and Grade Manager")
    print("1. Add a student")
    print("2. Update a student's mark")
    print("3. Search by student ID")
    print("4. Display averages and grades")
    print("5. Display highest average")
    print("6. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        student_id = input("Student ID: ")
        name = input("Student name: ")

        marks = []
        for i in range(3):
            while True:
                mark = float(input(f"Enter mark {i+1}: "))
                if 0 <= mark <= 100:
                    marks.append(mark)
                    break
                else:
                    print("Mark must be between 0 and 100.")

        students[student_id] = {"name": name, "marks": marks}
        print("Student added.")

    elif choice == "2":
        student_id = input("Student ID: ")
        if student_id in students:
            index = int(input("Which mark to update (1-3): ")) - 1
            if 0 <= index <= 2:
                while True:
                    mark = float(input("New mark: "))
                    if 0 <= mark <= 100:
                        students[student_id]["marks"][index] = mark
                        print("Mark updated.")
                        break
                    else:
                        print("Mark must be between 0 and 100.")
            else:
                print("Invalid mark number.")
        else:
            print("Student not found.")

    elif choice == "3":
        student_id = input("Student ID: ")
        if student_id in students:
            print(students[student_id])
        else:
            print("Student not found.")

    elif choice == "4":
        for student_id, data in students.items():
            total = 0
            for mark in data["marks"]:
                total += mark
            average = total / 3

            if average >= 80:
                grade = "A"
            elif average >= 70:
                grade = "B"
            elif average >= 60:
                grade = "C"
            elif average >= 50:
                grade = "D"
            else:
                grade = "F"

            print(
                student_id,
                data["name"],
                "Average:",
                round(average, 2),
                "Grade:",
                grade
            )

    elif choice == "5":
        highest_average = None
        top_students = []

        for student_id, data in students.items():
            total = 0
            for mark in data["marks"]:
                total += mark
            average = total / 3

            if highest_average is None or average > highest_average:
                highest_average = average
                top_students = [(student_id, data["name"])]
            elif average == highest_average:
                top_students.append((student_id, data["name"]))

        if highest_average is None:
            print("No student records available.")
        else:
            print("Highest Average:", round(highest_average, 2))
            for student_id, name in top_students:
                print(student_id, name)

    elif choice == "6":
        print("Exiting Student Record Manager.")
        break

    else:
        print("Invalid choice.")

# Problem 20: Automated Voting System

candidates = {
    "alice": 0,
    "bob": 0,
    "charlie": 0
}

rejected_votes = 0

print("Voting System")
print("Enter candidate names (Alice, Bob, Charlie).")
print("The system will automatically process results after 3 votes.")

# Loop exactly 3 times instead of a while loop
for i in range(1, 4):
    vote = input(f"Vote {i}/3: ").lower()

    if vote in candidates:
        candidates[vote] += 1
    else:
        rejected_votes += 1

print("\nVote Count:")
for candidate, votes in candidates.items():
    print(candidate.capitalize(), ":", votes)

total_valid_votes = 0
for votes in candidates.values():
    total_valid_votes += votes

print("Total Valid Votes:", total_valid_votes)
print("Rejected Votes:", rejected_votes)

if total_valid_votes == 0:
    print("No valid votes were submitted.")
else:
    print("\nVote Percentages:")
    for candidate, votes in candidates.items():
        percentage = (votes / total_valid_votes) * 100
        print(candidate.capitalize(), ":", round(percentage, 2), "%")

    highest_votes = None
    winners = []

    for candidate, votes in candidates.items():
        if highest_votes is None or votes > highest_votes:
            highest_votes = votes
            winners = [candidate]
        elif votes == highest_votes:
            winners.append(candidate)

    if len(winners) == 1:
        print("Winner:", winners[0].capitalize())
    else:
        print("Tie between:", ", ".join(name.capitalize() for name in winners))