# -*- coding: utf-8 -*-
"""AMDS_Data_Cleaning_Lab_Excercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4DvCqfgrP115yBaHzfVEc9WLlftNqnz
"""

import pandas as pd
import numpy as np

# Read the Datasets
sales = pd.read_csv("/content/drive/MyDrive/AMDS Practice Datasets/sales_raw_dataset.csv")
students = pd.read_csv("/content/drive/MyDrive/AMDS Practice Datasets/students_raw_dataset.csv")

"""Q1: Reading the student CSV file and display the first seven rows."""

students.head(7)

"""Q2: Displaying number of rows and columns in both datasets."""

print("Student Dataset Shape:", students.shape)
print("Sales Dataset Shape:", sales.shape)

"""Q3: Listing all student rows with missing values."""

students[students.isnull().any(axis=1)]

"""Q4: Counting missing values in every student column."""

students.isnull().sum()

"""Q5: Finding duplicated Student IDs."""

students[students.duplicated(subset="StudentID", keep=False)]

"""Q6: Students with ages outside 16 to 100."""

students[(students["Age"] < 16) | (students["Age"] > 100)]

"""Q7: Invalid attendance values."""

students[
    (students["Attendance"] < 0) |
    (students["Attendance"] > 100)
]

"""Q8: Converting Physics column to numeric"""

students["Physics"] = pd.to_numeric(
    students["Physics"],
    errors="coerce"
)
students["Physics"]

"""Q9: Replacing missing ages using median."""

valid_age = students["Age"].between(16,100)

median_age = students.loc[
    valid_age,
    "Age"
].median()

students.loc[
    students["Age"].isna(),
    "Age"
] = median_age

students["Age"]

"""Q10:Standardizing Gender."""

students["Gender"] = (
    students["Gender"]
    .astype(str)
    .str.strip()
    .str.upper()
)

gender_map = {
    "M":"M",
    "MALE":"M",
    "F":"F",
    "FEMALE":"F"
}

students["Gender"] = (
    students["Gender"]
    .map(gender_map)
    .fillna("Unknown")
)

students["Gender"].unique()

"""Q11: Remove duplicate Student IDs."""

students = students.drop_duplicates(
    subset="StudentID",
    keep="first"
)

students.shape

"""Q12: Calculating average mark."""

subjects = [
    "Math",
    "Physics",
    "Programming"
]

students["Average"] = students[
    subjects
].mean(axis=1)

students[["StudentID","Average"]]

"""Q13: Assigning Pass or Fail."""

students["Result"] = np.where(
    students["Average"] >= 40,
    "Pass",
    "Fail"
)
students[["StudentID","Average","Result"]]

"""Q14: Grade Assignment"""

def grade(avg):

    if avg >= 80:
        return "A"

    elif avg >= 70:
        return "B"

    elif avg >= 60:
        return "C"

    elif avg >= 50:
        return "D"

    else:
        return "F"

students["Grade"] = students["Average"].apply(grade)

students[["StudentID","Average","Grade"]]

"""Q15: Identifying duplicate Order IDs."""

sales[
    sales.duplicated(
        subset="OrderID",
        keep=False
    )
]

"""Q16: Finding Invalid Month values."""

valid_months = [
    "Jan","Feb","Mar","Apr",
    "May","Jun","Jul","Aug",
    "Sep","Oct","Nov","Dec"
]

sales[
    ~sales["Month"].isin(valid_months)
]

"""Q17: Replacing nonpositive Quantity."""

sales["Quantity"] = pd.to_numeric(
    sales["Quantity"],
    errors="coerce"
)

median_qty = sales.loc[
    sales["Quantity"]>0,
    "Quantity"
].median()

sales.loc[
    (sales["Quantity"]<=0) |
    (sales["Quantity"].isna()),
    "Quantity"
] = median_qty

sales["Quantity"]

"""Q18: Replacing nonpositive or missing Unit Price."""

sales["UnitPrice"] = pd.to_numeric(
    sales["UnitPrice"],
    errors="coerce"
)

median_price = sales.loc[
    sales["UnitPrice"]>0,
    "UnitPrice"
].median()

sales.loc[
    (sales["UnitPrice"]<=0) |
    (sales["UnitPrice"].isna()),
    "UnitPrice"
] = median_price

sales["UnitPrice"]

"""Q19: Calculating TotalSales"""

sales["TotalSales"] = (
    sales["Quantity"] *
    sales["UnitPrice"]
)

sales[["OrderID","TotalSales"]]

"""Q20: Saving cleaned CSV files."""

students.to_csv(
    "students_cleaned_dataset.csv",
    index=False
)

sales.to_csv(
    "sales_cleaned_dataset.csv",
    index=False
)

"""Q21: Saving raw and cleaned datasets into Excel."""

with pd.ExcelWriter(
    "Python_Lab_Cleaned_Datasets.xlsx",
    engine="openpyxl"
) as writer:

    pd.read_csv("/content/drive/MyDrive/AMDS Practice Datasets/students_raw_dataset.csv").to_excel(
        writer,
        sheet_name="Students_Raw",
        index=False
    )

    students.to_excel(
        writer,
        sheet_name="Students_Clean",
        index=False
    )

    pd.read_csv("/content/drive/MyDrive/AMDS Practice Datasets/sales_raw_dataset.csv").to_excel(
        writer,
        sheet_name="Sales_Raw",
        index=False
    )

    sales.to_excel(
        writer,
        sheet_name="Sales_Clean",
        index=False
    )

"""Q22: Verifying duplicate IDs."""

print(
    students["StudentID"].duplicated().sum()
)

print(
    sales["OrderID"].duplicated().sum()
)

"""Q23: Verifying no missing numerical values."""

print(
    students.select_dtypes(
        include=np.number
    ).isnull().sum()
)

print(
    sales.select_dtypes(
        include=np.number
    ).isnull().sum()
)

"""Q24: Finding Average student mark by department."""

students.groupby(
    "Department"
)["Average"].mean().sort_values(
    ascending=False
)

"""Q25: Finding Total sales by Product and Region."""

print("Sales by Product")

print(
    sales.groupby(
        "Product"
    )["TotalSales"].sum()
)

print()

print("Sales by Region")

print(
    sales.groupby(
        "Region"
    )["TotalSales"].sum()
)